# Generated by Django 2.1.5 on 2019-01-30 15:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Title')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('summary', models.TextField(blank=True, help_text='Short summary about the person')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='Person bio/description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'People',
                'verbose_name': 'Person',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
