# Generated by Django 2.1.5 on 2019-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_people', '0002_rename_field_summary_on_person_to_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='title',
            new_name='_title',
        ),
    ]
