# Generated by Django 2.1.5 on 2019-02-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_core', '0002_analyticssettings_footersettings_indexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
