# Generated by Django 2.1.7 on 2019-03-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_core', '0010_add_display_to_embedblock'),
        ('kdl_wagtail_core', '0011_auto_20190319_1311'),
    ]

    operations = [
    ]
