# Generated by Django 2.1.7 on 2019-05-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_core', '0015_auto_20190505_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusfield',
            options={},
        ),
        migrations.AlterField(
            model_name='contactusfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('captcha', 'Captcha')], max_length=16, verbose_name='field type'),
        ),
    ]
