# Generated by Django 2.2.10 on 2020-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_core', '0019_richtextblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
