# Generated by Django 3.2.8 on 2021-10-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_core', '0023_proxypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypage',
            name='target_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_page', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='proxypage',
            name='target_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL'),
        ),
    ]
