# Generated by Django 2.2.1 on 2019-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='key',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibliography',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
