# Generated by Django 2.2.1 on 2019-05-08 12:57

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0002_add_fields_key_and_url_to_basebibliography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='citation',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
