# Generated by Django 2.2.1 on 2019-05-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0003_alter_field_citation_on_bibliography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'ordering': ['order'], 'verbose_name': 'Biblography', 'verbose_name_plural': 'Bibliography'},
        ),
        migrations.AddField(
            model_name='bibliography',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
