# Generated by Django 2.2.1 on 2019-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0004_add_field_order_to_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
