# Generated by Django 2.2.1 on 2019-05-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0005_add_fields_author_and_title_to_bibliography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliography',
            name='title',
        ),
    ]
