# Generated by Django 2.2.1 on 2019-05-16 10:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0006_remove_bibliography_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='citation_short',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
